import BookReviewTemplate from "../../BookReviewTemplate.js";

const TaoLin_Taipei = (props) => {
    const title = "Tao Lin - Taipei (2013)";
    const date = "8-1-2021";
    const content = (
        <div>
            <p>Taipei is one of the newer books I think I’ve read, or at least the newest fiction book which is trying to be large and have some kind of meaning behind it. I think it definitely sets itself up to be such a book but, maybe obviously, time will be the real critique here. Taipei more so than most books sets its stage around technology and drugs as a way to ground its premises. These facets are expressive to me, having lived through this period as a person or known a person who fell victim to these vices, but I don’t know if even less then a decade later these references play as strong a role anymore. The talk about carrying around a laptop to take video sounds a little dated, the strong references to some of the websites mostly still relevant but feel a little tired how they’re presented, and there seems to be a lack of openness surrounding talking about the internet which I feel has become a part of daily life now.
            <br/>
            Paul the main character is supposed to represent or parallel the author, Tao Lin’s, life. He’s more often unlikeable but gives the story a center of gravity that would otherwise feel lost in the dreamlike New York that the majority of the book takes place in. Paul is an author with what we can assume to be little responsibilities, letting him spend his time freely. This mainly means that he’s sleeping in and at odd hours, going to parties, doing drugs, looking at the internet, falling in and out of relationships, and generally watching life pass him by in a sort of New York Zen kind of way.
            <br/>
            The drug intake in the book feels strikingly modern. It exists in a sort of Watts meets McKenna meets depressed post grad student kind of way. The story starts with Paul drinking a little (or a little more) at parties and slowly ramping up until the end of the book has Paul doing heroin while also on several other drugs, all while he condemns doctors and alcohol. I think this way of doing drugs is maybe the best part of the book. It at no time condemns these drugs (we can assume that the author's view is the same as the main character) but it also shows them as a mixed blessing as Paul and his friends spiral through an early life crisis. I don’t agree with Paul's actions but it's the part of the book I feel has only become more relevant. Paul’s mother’s plees for him to not take drugs is of course heard by the reader, Paul, and Tao Lin.
            <br/>
            The book seems to revolve around two visits to Taipei. The first at the beginning of the book with just Paul visiting his family and the second with his new wife. The first time it showcases Paul trying to live with his parents again and taking his mothers harsh questions like: why do all your girlfriends leave you. The second, which takes place about a year later, he arrives with his wife, seemingly fulfilling his mother’s dream, but the trip goes south at some point and, while they arrived on good terms, by the end it seems a cold reality sets in on the newlyweds. His second trip is an answer to his mother’s question which he had previously left unanswered. Paul and his wife, Erin, see there relationship continue to dissolve and they both seem unhappy constantly, seeing each other rarely and taking drugs the whole time they’re together.The story does a good job of making no one look innocent and shocking the reader when you realize how deep a grave they’ve dug themselves without barely realizing it. 
            <br/>
            Taipei’s sense of morality is all over the place and that’s probably the most convincing case that the story was really based on true events. Paul definitely has strong feelings. He feels that drugs and food are best natural and taken with freedom and better without any sort of middleman. His relationship advice seems to be do what you want and tell the truth. Neither of these things seem to lead down any really amazing roads but the book seems to be about some greater sense of happiness and fulfilled being, one that is happy with doing nothing or doing everything or somewhere inbetween. It definitely feels zen but it also feels desperate. You can’t help but feel like Paul, deep down inside, is really going through things, things which the book doesn’t spend time to enlighten us with, likely because it’s the author’s feelings and to him they seem unknowable. We can also assume that Paul’s character is writing this whole time (maybe even writing this very book!) and there’s something to be said for why that’s left out. It’s possible that it’s left out because it would make him feel more functional and Tao Lin doesn’t want that. 
            <br/>
            The Paul at the end of the book on paper would be a different person (doing hard drugs, married, etc) but he’s really just reinforced himself as the same person. Just like at the end of the story, he’s leaving a relationship,has a weird relationship with his parents, and is (sorta) friends with odd people who he doesn’t feel any extreme attachment to. The story seems to encourage a cyclic view of a generation where the way they grow up shapes who they are and what they’re like and nothing will change that. 
            <br/>
            I think the biggest problem I have with Tao Lin’s story is that the relationship ties and time he puts into things doesn’t seem to matter. I feel like there is more inherent historical importance in one’s everyday actions then Paul chooses to recognize, though he participates in little things which follow this philosophy (like his rootsy medicines and fruits). You would think he would have more innate purpose with larger things like relationships and the like. Maybe it is just Paul overthinking things.
            </p>
        </div>
    );
    return <BookReviewTemplate 
        title={title} 
        date={date}
        content={content}
        />
}
export default TaoLin_Taipei;